@HostAddress = http://localhost:5283
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InRlc3R1c2VyIiwibmJmIjoxNzgyOTE1NTM3LCJleHAiOjE3ODI5MTkxMzcsImlhdCI6MTc4MjkxNTUzNywiaXNzIjoiU1dFTjJUb3VyUGxhbm5lci5BcGkiLCJhdWQiOiJTV0VOMlRvdXJQbGFubmVyLkZyb250ZW5kIn0.GmpE-c1Ao8LpH6knsfdtq9D_hICWwmDGaOdye2DaVNI
@TourId = 16
@LogId = 2

POST {{HostAddress}}/api/auth/register
Content-Type: application/json

{
    "username": "testuser",
    "password": "TestPassword123!"
}

###

# @name login false credentials
POST {{HostAddress}}/api/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpass"
}

###

# @name login valid credentials
POST {{HostAddress}}/api/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "TestPassword123!"
}

###

# Get all tours (popularity und childfriendliness fehlen noch)
GET {{HostAddress}}/api/tours/
Authorization: Bearer {{Token}}

###

# Search for plus sign

GET {{HostAddress}}/api/tours/?search=berlin
Authorization: Bearer {{Token}}

###

# create a new tour

POST {{HostAddress}}/api/tours/
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "name": "coole tour",
  "description": "coole beschreibung",
  "from": "Berlin",
  "to": "Hamburg",
  "transportType": 2,
  "distance": null,
  "estimatedTime": null,
  "routeInformation": "https://www.google.com/maps/dir/Berlin/Hamburg/@52.4416976,10.4899138,7z/data=!3m1!4b1!4m13!4m12!1m5!1m1!1s0x47a84e9caa9fbbf3:0x420d2cbbd8e5e7c!2m2!1d13.404954!2d52.5200066!1m5!1m1!1s0x47b18eaaea9a7b71:0x422cbbd8e5e7c!2m2!1d9.9936824!2d53.5510846"
}

###

# get tour by id (popularity und childfriendliness fehlen noch)

GET {{HostAddress}}/api/tours/{{TourId}}
Authorization: Bearer {{Token}}

###

# update tour

PUT {{HostAddress}}/api/tours/{{TourId}}
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "name": "coole geupdatete tour",
  "description": "coole geupdatete beschreibung",
  "from": "Wien",
  "to": "Hamburg",
  "transportType": 2,
  "distance": 289,
  "estimatedTime": "03:00:00",
  "routeInformation": "https://www.google.com/maps/dir/Berlin/Hamburg/@52.4416976,10.4899138,7z/data=!3m1!4b1!4m13!4m12!1m5!1m1!1s0x47a84e9caa9fbbf3:0x420d2cbbd8e5e7c!2m2!1d13.404954!2d52.5200066!1m5!1m1!1s0x47b18eaaea9a7b71:0x422cbbd8e5e7c!2m2!1d9.9936824!2d53.5510846"
}

###

# delete tour (logs löschen fehlt hier noch)

DELETE {{HostAddress}}/api/tours/{{TourId}}
Authorization: Bearer {{Token}}

###

# export tours and logs as json

GET {{HostAddress}}/api/tours/export
Authorization: Bearer {{Token}}

###

# import tours and logs from json

POST {{HostAddress}}/api/tours/import
Authorization: Bearer {{Token}}
Content-Type: application/json

[
  {
    "id": 0,
    "name": "coole tour",
    "description": "coole beschreibung",
    "from": "Berlin",
    "to": "Hamburg",
    "transportType": "Car",
    "distance": 289,
    "estimatedTime": "03:00:00",
    "routeInformation": "https://www.google.com/maps/dir/Berlin/Hamburg/@52.4416976,10.4899138,7z/data=!3m1!4b1!4m13!4m12!1m5!1m1!1s0x47a84e9caa9fbbf3:0x420d2cbbd8e5e7c!2m2!1d13.404954!2d52.5200066!1m5!1m1!1s0x47b18eaaea9a7b71:0x422cbbd8e5e7c!2m2!1d9.9936824!2d53.5510846",
    "userId": 0,
    "logs": []
  },
  {
    "id": 1,
    "name": "coole tour",
    "description": "coole beschreibung",
    "from": "Berlin",
    "to": "Hamburg",
    "transportType": "Car",
    "distance": 289,
    "estimatedTime": "03:00:00",
    "routeInformation": "https://www.google.com/maps/dir/Berlin/Hamburg/@52.4416976,10.4899138,7z/data=!3m1!4b1!4m13!4m12!1m5!1m1!1s0x47a84e9caa9fbbf3:0x420d2cbbd8e5e7c!2m2!1d13.404954!2d52.5200066!1m5!1m1!1s0x47b18eaaea9a7b71:0x422cbbd8e5e7c!2m2!1d9.9936824!2d53.5510846",
    "userId": 0,
    "logs": [
      {
        "id": 4,
        "tourId": 1,
        "time": "2023-01-01T00:00:00Z",
        "comment": "This is a test log.",
        "difficulty": 3.1,
        "totalDistance": 100,
        "totalTime": "02:30:00",
        "rating": 4.7
      }
    ]
  }
]

###

# get all logs for a tour

GET {{HostAddress}}/api/tours/{{TourId}}/logs
Authorization: Bearer {{Token}}

###

# search for logs by term

GET {{HostAddress}}/api/tours/{{TourId}}/logs/search?term=test
Authorization: Bearer {{Token}}

###

# create a new log for a tour

POST {{HostAddress}}/api/logs/
Authorization: Bearer {{Token}}
Content-Type: application/json

{
    "tourId": {{TourId}},
    "time": "2023-01-01T00:00:00Z",
    "comment": "This is a test log.",
    "difficulty": 3.1,
    "totalDistance": 100,
    "totalTime": "02:30:00",
    "rating": 4.7
}

###

# get a log by id

GET {{HostAddress}}/api/logs/{{LogId}}
Authorization: Bearer {{Token}}

###

# update a log

PUT {{HostAddress}}/api/logs/{{LogId}}
Authorization: Bearer {{Token}}
Content-Type: application/json

{
    "tourId": {{TourId}},
    "time": "2023-01-02T00:00:00Z",
    "comment": "This is an updated test log.",
    "difficulty": 4.2,
    "totalDistance": 120,
    "totalTime": "03:00:00",
    "rating": 4.9
}

###

# delete a log

DELETE {{HostAddress}}/api/logs/{{LogId}}
Authorization: Bearer {{Token}}

###