@SWEN2TourPlanner.Api_HostAddress = http://localhost:5283

POST http://localhost:5283/api/auth/register
Content-Type: application/json

{
    "username": "testuser",
    "password": "TestPassword123!"
}

###
